CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2 -I./src
SRCDIR = src
TESTDIR = tests

MAIN_TARGET = db_main
TEST_MEMTABLE_TARGET = test_memtable
TEST_DATABASE_TARGET = test_database
TEST_SST_FLUSH_TARGET = test_sst_flush
TEST_SST_TARGET = test_sst
TEST_BUFFER_POOL_TARGET = test_buffer_pool
TEST_LSM_TREE_TARGET = test_lsm_tree
TEST_BUFFER_POOL_INTEGRATION_TARGET = test_buffer_pool_integration
TEST_SEQUENTIAL_FLOODING_TARGET = test_sequential_flooding
TEST_BLOOM_FILTER_TARGET = test_bloom_filter

MAIN_SOURCES = main.cpp
TEST_MEMTABLE_SOURCES = $(TESTDIR)/test_memtable.cpp $(TESTDIR)/test_framework.cpp
TEST_DATABASE_SOURCES = $(TESTDIR)/test_database.cpp $(TESTDIR)/test_framework.cpp
TEST_SST_FLUSH_SOURCES = $(TESTDIR)/test_sst_flush.cpp $(TESTDIR)/test_framework.cpp
TEST_SST_SOURCES = $(TESTDIR)/test_sst.cpp $(TESTDIR)/test_framework.cpp
TEST_BUFFER_POOL_SOURCES = $(TESTDIR)/test_buffer_pool.cpp $(TESTDIR)/test_framework.cpp
TEST_LSM_TREE_SOURCES = $(TESTDIR)/test_lsm_tree.cpp $(TESTDIR)/test_framework.cpp
TEST_BUFFER_POOL_INTEGRATION_SOURCES = $(TESTDIR)/test_buffer_pool_integration.cpp $(TESTDIR)/test_framework.cpp
TEST_SEQUENTIAL_FLOODING_SOURCES = $(TESTDIR)/test_sequential_flooding.cpp $(TESTDIR)/test_framework.cpp
TEST_BLOOM_FILTER_SOURCES = $(TESTDIR)/test_bloom_filter.cpp $(TESTDIR)/test_framework.cpp

HEADERS = $(SRCDIR)/memtable/memtable.h $(SRCDIR)/core/database.h $(SRCDIR)/storage/sst.h $(SRCDIR)/buffer/buffer_pool.h $(SRCDIR)/../utils/bloom_filter.h
IMPL_FILES = $(SRCDIR)/memtable/memtable.cpp $(SRCDIR)/core/database.cpp $(SRCDIR)/storage/sst.cpp $(SRCDIR)/buffer/buffer_pool.cpp
TEST_HEADERS = $(TESTDIR)/test_framework.h

all: $(MAIN_TARGET) $(TEST_MEMTABLE_TARGET) $(TEST_DATABASE_TARGET) $(TEST_SST_FLUSH_TARGET) $(TEST_SST_TARGET) $(TEST_BUFFER_POOL_TARGET) $(TEST_LSM_TREE_TARGET) $(TEST_BUFFER_POOL_INTEGRATION_TARGET) $(TEST_SEQUENTIAL_FLOODING_TARGET) $(TEST_BLOOM_FILTER_TARGET)

$(MAIN_TARGET): $(MAIN_SOURCES) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(MAIN_TARGET) $(MAIN_SOURCES)

$(TEST_MEMTABLE_TARGET): $(TEST_MEMTABLE_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_MEMTABLE_TARGET) $(TEST_MEMTABLE_SOURCES)

$(TEST_DATABASE_TARGET): $(TEST_DATABASE_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_DATABASE_TARGET) $(TEST_DATABASE_SOURCES)

$(TEST_SST_FLUSH_TARGET): $(TEST_SST_FLUSH_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_SST_FLUSH_TARGET) $(TEST_SST_FLUSH_SOURCES)

$(TEST_SST_TARGET): $(TEST_SST_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_SST_TARGET) $(TEST_SST_SOURCES)

$(TEST_BUFFER_POOL_TARGET): $(TEST_BUFFER_POOL_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_BUFFER_POOL_TARGET) $(TEST_BUFFER_POOL_SOURCES)

$(TEST_LSM_TREE_TARGET): $(TEST_LSM_TREE_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_LSM_TREE_TARGET) $(TEST_LSM_TREE_SOURCES)

$(TEST_BUFFER_POOL_INTEGRATION_TARGET): $(TEST_BUFFER_POOL_INTEGRATION_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_BUFFER_POOL_INTEGRATION_TARGET) $(TEST_BUFFER_POOL_INTEGRATION_SOURCES)

$(TEST_SEQUENTIAL_FLOODING_TARGET): $(TEST_SEQUENTIAL_FLOODING_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_SEQUENTIAL_FLOODING_TARGET) $(TEST_SEQUENTIAL_FLOODING_SOURCES)

$(TEST_BLOOM_FILTER_TARGET): $(TEST_BLOOM_FILTER_SOURCES) $(TEST_HEADERS) $(HEADERS) $(IMPL_FILES)
	$(CXX) $(CXXFLAGS) -o $(TEST_BLOOM_FILTER_TARGET) $(TEST_BLOOM_FILTER_SOURCES)

test: $(TEST_MEMTABLE_TARGET) $(TEST_DATABASE_TARGET) $(TEST_SST_FLUSH_TARGET) $(TEST_SST_TARGET) $(TEST_BUFFER_POOL_TARGET) $(TEST_LSM_TREE_TARGET) $(TEST_BUFFER_POOL_INTEGRATION_TARGET) $(TEST_SEQUENTIAL_FLOODING_TARGET) $(TEST_BLOOM_FILTER_TARGET)
	./$(TEST_MEMTABLE_TARGET)
	./$(TEST_DATABASE_TARGET)
	./$(TEST_SST_FLUSH_TARGET)
	./$(TEST_SST_TARGET)
	./$(TEST_BUFFER_POOL_TARGET)
	./$(TEST_LSM_TREE_TARGET)
	./$(TEST_BUFFER_POOL_INTEGRATION_TARGET)
	./$(TEST_SEQUENTIAL_FLOODING_TARGET)
	./$(TEST_BLOOM_FILTER_TARGET)

run: $(MAIN_TARGET)
	./$(MAIN_TARGET)

clean:
	rm -f $(MAIN_TARGET) $(TEST_MEMTABLE_TARGET) $(TEST_DATABASE_TARGET) $(TEST_SST_FLUSH_TARGET) $(TEST_SST_TARGET) $(TEST_BUFFER_POOL_TARGET) $(TEST_LSM_TREE_TARGET) $(TEST_BUFFER_POOL_INTEGRATION_TARGET) $(TEST_SEQUENTIAL_FLOODING_TARGET) $(TEST_BLOOM_FILTER_TARGET)

rebuild: clean all

.PHONY: all test run clean rebuild

debug: CXXFLAGS += -g -DDEBUG
debug: $(MAIN_TARGET) $(TEST_MEMTABLE_TARGET) $(TEST_DATABASE_TARGET) $(TEST_SST_FLUSH_TARGET) $(TEST_SST_TARGET) $(TEST_BUFFER_POOL_TARGET) $(TEST_LSM_TREE_TARGET) $(TEST_BUFFER_POOL_INTEGRATION_TARGET) $(TEST_SEQUENTIAL_FLOODING_TARGET) $(TEST_BLOOM_FILTER_TARGET)

release: CXXFLAGS += -DNDEBUG
release: $(MAIN_TARGET) $(TEST_MEMTABLE_TARGET) $(TEST_DATABASE_TARGET) $(TEST_SST_FLUSH_TARGET) $(TEST_SST_TARGET) $(TEST_BUFFER_POOL_TARGET) $(TEST_LSM_TREE_TARGET) $(TEST_BUFFER_POOL_INTEGRATION_TARGET) $(TEST_SEQUENTIAL_FLOODING_TARGET) $(TEST_BLOOM_FILTER_TARGET)
